# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.IntegerField(default=0),
        ),
    ]
