# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200525_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_file',
            name='filee',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
