# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200708_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_file',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
