# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pdf_file_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_file',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
