# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pdf_file_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_file',
            name='gradd',
            field=models.CharField(default='No Grade', max_length=3),
        ),
    ]
