# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200708_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='No first name', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='no last name', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='from_datetime',
            field=models.DateTimeField(null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='to_datetime',
            field=models.DateTimeField(null=True, verbose_name='To'),
        ),
    ]
