# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200708_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_file',
            old_name='filee',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='pdf_file',
            old_name='teacher',
            new_name='lecturer',
        ),
    ]
