# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200708_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To'),
        ),
    ]
