# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_pdf_file_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
