# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200708_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='from_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
