# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200708_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='from_datetime',
        ),
    ]
