# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_teacher_from_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='from_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
