# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_teacher_from_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission_datetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='from_datetime',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='to_datetime',
        ),
        migrations.AddField(
            model_name='teacher',
            name='datetime',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Submission_datetime'),
        ),
    ]
