# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200709_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission_datetime',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
