# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200709_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_file',
            name='time',
        ),
    ]
