# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200709_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_file',
            name='gradd',
            field=models.CharField(default='No Grade yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(default='empty', max_length=10),
        ),
    ]
